name: Release

on:
  push:
    branches: [main]

jobs:
  build:
    uses: ./.github/workflows/continuous-integration.yml

  deploy:
    runs-on: ubuntu-latest
    needs: build

    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      
      - name: Login to Docker Hub
        run: docker login -u ${{ secrets.DOCKER_USERNAME }} -p ${{ secrets.DOCKER_PASSWORD }}
  
      - name: Build and tag Docker image
        run: docker build -t StatlerWaldorfCorp.TeamService:latest .
  
      - name: Publish image to Docker Hub
        run: docker push your-image-name:your-tag
