name: Release

on:
  push:
    branches: [main]

jobs:
  build:
    uses: ./.github/workflows/continuous-integration.yml

  deploy:
    runs-on: ubuntu-latest
    needs: build

    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Set working directory
        run: cd ./src/StatlerWaldorfCorp.TeamService
      
      - name: Login to Docker Hub
        run: docker login -u ${{ secrets.DOCKER_USERNAME }} -p ${{ secrets.DOCKER_PASSWORD }}
  
      - name: Build and tag Docker image
        run: docker build -t statlerwaldorfcorp.teamservice:latest .
        # working-directory: ./src/StatlerWaldorfCorp.TeamService
  
      - name: Publish image to Docker Hub
        run: docker push ${{ secrets.DOCKER_USERNAME }}/statlerwaldorfcorp.teamservice:latest
        # working-directory: ./src/StatlerWaldorfCorp.TeamService
